###
GET http://localhost:8080/api/v1/events
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJ2b2x1bnRlZXJodWIuY29tIiwic3ViIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJleHAiOjE3NjI0MDYyOTUsImlhdCI6MTc2MjQwMjY5NSwianRpIjoiZmJmZDhhZDMtNTcxNi00MjhlLTlhNGEtNGMwZGYyNjQ1ZWJhIiwicm9sZXMiOlsiQURNSU4iXX0.Bp_nMnsnSVlDlYiUjyV7KfbF0vVA4RtgpYHKOQR77_BQDPNsn6sCNe0Pe7o-tg83ArR7IWPVNiE5g3Xw5_Gnog
###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin"
}

###
PUT http://localhost:8080/api/v1/events/690a185274efe5d9b0e0b29a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJ2b2x1bnRlZXJodWIuY29tIiwic3ViIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJleHAiOjE3NjI0MDYyOTUsImlhdCI6MTc2MjQwMjY5NSwianRpIjoiZmJmZDhhZDMtNTcxNi00MjhlLTlhNGEtNGMwZGYyNjQ1ZWJhIiwicm9sZXMiOlsiQURNSU4iXX0.Bp_nMnsnSVlDlYiUjyV7KfbF0vVA4RtgpYHKOQR77_BQDPNsn6sCNe0Pe7o-tg83ArR7IWPVNiE5g3Xw5_Gnog

{
  "title": "test2",
  "description": "updated",
  "date": "2025-11-03",
  "location": "DaNang"
}

###Post Event
POST http://localhost:8080/api/v1/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJ2b2x1bnRlZXJodWIuY29tIiwic3ViIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJleHAiOjE3NjMwMDQxNzIsImlhdCI6MTc2MzAwMDU3MiwianRpIjoiNTdhMDUwOTUtMzhkNy00MDljLWFkNTctZTM0MTA0ZWZhM2RjIiwicm9sZXMiOlsiQURNSU4iXX0.AEA-8IlcwgrmfkHBKR0GioHxNhhz1snbM4aVdjG444kmdKqKu2W-T7eTd-zD1BGmrsnBC8tTMEvhCQYmRK4WzQ

{
  "title": "test4",
  "description": "namoadidaphat",
  "date": "2025-06-05",
  "location": "HaNoi"
}

###
PUT http://localhost:8080/api/v1/events/690a185274efe5d9b0e0b29a/approve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJ2b2x1bnRlZXJodWIuY29tIiwic3ViIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJleHAiOjE3NjI0MDYyOTUsImlhdCI6MTc2MjQwMjY5NSwianRpIjoiZmJmZDhhZDMtNTcxNi00MjhlLTlhNGEtNGMwZGYyNjQ1ZWJhIiwicm9sZXMiOlsiQURNSU4iXX0.Bp_nMnsnSVlDlYiUjyV7KfbF0vVA4RtgpYHKOQR77_BQDPNsn6sCNe0Pe7o-tg83ArR7IWPVNiE5g3Xw5_Gnog

{
  "status": "approved",
  "reason": "good content"
}

### Update role
PUT http://localhost:8080/api/v1/roles/ADMIN
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJ2b2x1bnRlZXJodWIuY29tIiwic3ViIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJleHAiOjE3NjI0MDYyOTUsImlhdCI6MTc2MjQwMjY5NSwianRpIjoiZmJmZDhhZDMtNTcxNi00MjhlLTlhNGEtNGMwZGYyNjQ1ZWJhIiwicm9sZXMiOlsiQURNSU4iXX0.Bp_nMnsnSVlDlYiUjyV7KfbF0vVA4RtgpYHKOQR77_BQDPNsn6sCNe0Pe7o-tg83ArR7IWPVNiE5g3Xw5_Gnog

{
  "permissions": ["POST_EVENT", "UPDATE_EVENT", "DELETE_EVENT", "APPROVE_EVENT"]
}